name: GoldmanResourceWorlds
version: ${version}
main: lee.code.resourceworlds.ResourceWorlds
api-version: 1.20
author: Lee
folia-supported: true
commands:
  resourceworld:
    description: Open resource world menu.
    permission: resourceworld.command.resourceworld
    usage: "/resourceworld"
